name: Build and deploy Node.js app to Azure Web App - uniflow-notification-service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build application
        run: pnpm run build

      - name: Run tests
        run: pnpm run test --passWithNoTests

      # CRÍTICO: Instalar SOLO dependencias de producción en una carpeta limpia
      - name: Install production dependencies
        run: |
          mkdir -p deployment
          cp -r dist deployment/
          cp package.json deployment/
          cp pnpm-lock.yaml deployment/
          cd deployment
          pnpm install --prod --frozen-lockfile

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: deployment

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: Production

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'uniflow-notification-service'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C65851A2C29B4D3ABDC3CFF98CB1EF0F }}