# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - uniflow-notification-service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: pnpm install, build, and test
        env:
          # Environment Variables
          ACCOUNTNAME: ${{ vars.ACCOUNTNAME }}
          AZURE_COMMUNICATION_SENDER_ADDRESS: ${{ vars.AZURE_COMMUNICATION_SENDER_ADDRESS }}
          AZURE_NOTIFICATION_HUB_NAME: ${{ vars.AZURE_NOTIFICATION_HUB_NAME }}
          EMAIL_ENABLED: ${{ vars.EMAIL_ENABLED }}
          FRONTEND_URL: ${{ vars.FRONTEND_URL }}
          QUEUE_NAME: ${{ vars.QUEUE_NAME }}
          # Secrets
          AZURE_COMMUNICATION_CONNECTION_STRING: ${{ secrets.AZURE_COMMUNICATION_CONNECTION_STRING }}
          AZURE_NOTIFICATION_HUB_CONNECTION_STRING: ${{ secrets.AZURE_NOTIFICATION_HUB_CONNECTION_STRING }}
          AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: |
          pnpm install
          pnpm run build
          pnpm run test --passWithNoTests

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: Production

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'uniflow-notification-service'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C65851A2C29B4D3ABDC3CFF98CB1EF0F }}



