name: Build and deploy Node.js app to Azure Web App - uniflow-notification-service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        run: npm test -- --passWithNoTests

      # Crear package de deployment con node_modules de producción
      - name: Prepare deployment package
        run: |
          mkdir deployment
          cp -r dist deployment/
          cp package*.json deployment/
          cd deployment
          npm ci --production --ignore-scripts

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: deployment

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: Production

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'uniflow-notification-service'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C65851A2C29B4D3ABDC3CFF98CB1EF0F }}